<?php

declare(strict_types=1);

namespace App\Services\Telegram\Keyboard;

final class InlineKeyboard
{
    private array $rows = [];

    public static function make(): self
    {
        return new self();
    }

    /**
     * @param array ...$buttons Array of buttons generated by Button::class
     */
    public function addRow(array ...$buttons): self
    {
        $this->rows[] = $buttons;
        return $this;
    }

    public function toArray(): array
    {
        if (empty($this->rows)) {
            return [];
        }

        return [
            'inline_keyboard' => $this->rows,
        ];
    }
}
